config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :contacts, only: [:new]
  resources :items, only: [:index]
  resources :companies, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/companies/index.html.erb
<div class="company-info m-5">
  <table class="table table-bordered">
    <tr>
      <th>会社名</th>
      <td>
        <p>KNテクノロジーズ</p>
      </td>
    </tr>
    <tr>
      <th>代表</th>
      <td><p>西川　健二</p></td>
    </tr>
    <tr>
      <th>所在地</th>
      <td>
        <p>〒811-3114<br>
        福岡県古賀市舞の里４丁目１４番９号</p>
      </td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td>080-8552-6587</td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>kenji.nishikawa_kntech@ymt.bbiq.jp</td>
    </tr>
    <tr>
      <th>設立</th>
      <td> 2017年 7月</td>
    </tr>
      <th>事業内容</th>
      <td>
        <p>- 真空関連機器/装置</p><br>
        <p>- 真空ポンプ/メンテナンス</p><br>
        <p>- 中古実験機器/装置</p><br>
        <p>- 熱物製測定装置/熱分析装置/赤外線加熱路</p><br>
        <p>- 蒸着材料/スパッタリング用ターゲット</p><br>
        <p>- 樹脂加工製品</p><br>
        <p>- 金属加工品</p><br>
        <p>- ガラス加工品</p><br>
        <p>- その他、実験用機器設計制作</p>
      </td>
    </tr>
  </table>
</div>

app/views/contacts/new.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-center">
    <p class="h1">お問い合わせ</p>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form action="https://api.staticforms.xyz/submit" method="post">
        <input type="hidden" name="accessKey" value="アクセスキー">
        <input type="hidden" name="subject" value="件名">
        <input type="hidden" name="redirectTo" value="絶対パス">
        <div class="form-group">
          <label class="col-sm-4 col-form-label">会社名</label>
          <div class="col-sm-12">
            <input type="text" name="name" class="form-control" id="inputName">
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-4 col-form-label">お名前</label>
          <div class="col-sm-12">
            <input type="text" name="name" class="form-control" id="inputName">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail" class="col-sm-4 col-form-label">メールアドレス</label>
          <div class="col-sm-12">
            <input type="email" name="email" class="form-control" id="inputEmail">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail" class="col-sm-4 col-form-label">お電話</label>
          <div class="col-sm-12">
            <input type="tel" name="email" class="form-control" id="inputEmail">
          </div>
        </div>
        <div class="form-group">
          <label for="inputTextarea" class="col-sm-4 col-form-label">お問い合わせ内容</label>
          <div class="col-sm-12">
            <textarea name="message" rows="3" class="form-control" id="inputTextarea"></textarea>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary mb-2">送信</button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
    <header>
      <div class="navbar navbar-dark bg-dark">
        <div>
          <h1 class="text-white">ＫＮテクノロジーズ</h1>
        </div>
        <div class="navbar">
          <ul class="nav nav-pills nav-justified">
            <li class="nav-item">
              <%=link_to '会社概要', companies_path, class: [:btn, :"btn-primary"] %>
            </li>
            <li class="nav-item">
              <%=link_to '商品一覧', items_path, class: [:btn, :"mx-3", :"btn-primary"] %>
            </li>
            <li class="nav-item">
              <%=link_to 'お問い合わせ', new_contact_path, class: [:btn, :"btn-primary"] %>
            </li>
          </ul>
        </div>
      </div>
    </header>

    <div class="contents">
      <div class="jumbotron jumbotron-fluid main-image">
        <div class="container">
          <h1 class="display-3">Fluid jumbotron</h1>
          <p class="lead">This is a modified jumbotron that occupies
                          the entire horizontal space of its parent.</p>
        </div>
      </div>  
      <div class="container">
        <div class="upper-content ">
          a<!-- 『新着情報』を表示する -->
        </div>
        <div class="middle-content">
          b<!-- 『スタイリスト紹介』を表示する -->
        </div>
        <div class="bottom-content">
         b <!-- 『フォーム』を表示する -->
        </div>
      </div>
    </div>

    <footer>
    </footer>

app/views/items/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <%# <% if user_signed_in? %> 
      <div class="greeting">
        こんにちは、
        <%# <%= link_to "#{current_user.name}さん", user_path(@prototype), class: :greeting__link %> 
      </div>
    <%# <% end %> 
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# <%= render partial: 'prototype', collection: @prototypes %> 
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kntech</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>